# User          - 01
# Matching      - 02
# Question      - 03
# Chat          - 04
# Video Call    - 05
# Socket        - 06
# Collaboration - 07

version: "3"
services:
  socket:
    container_name: socket-service
    build:
      context: ./services/socket-service
      dockerfile: Dockerfile
    ports:
      - "5006:5000"
    env_file:
      - ./services/socket-service/.env
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - socket_service_network
      - api_network
      - kafka_network

  matching:
    container_name: matching-service
    build:
      context: ./services/matching-service
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    env_file:
      - ./services/matching-service/.env
    links:
      - postgres_matching_service
    depends_on:
      broker:
        condition: service_healthy
    networks:
      - matching_service_network
      - api_network
      - kafka_network

  postgres_matching_service:
    image: postgres:latest
    container_name: postgres-matching-service
    volumes:
      - progresDB:/data/postgres/matching-service
    env_file:
      - ./services/matching-service/.env
    networks:
      - matching_service_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    ports:
      - "2181:2181"
    networks:
      - kafka_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"
    networks:
      - kafka_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  matching_service_network:
    driver: bridge

  socket_service_network:
    driver: bridge

  kafka_network:
    driver: bridge

  api_network:
    driver: bridge

volumes:
  progresDB:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
