apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-service
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: socket-service
  template:
    metadata:
      labels:
        app: socket-service
    spec:
      containers:
        - name: socket-service
          image: socket-service-image:tag  # Replace with the actual image
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
          envFrom:
            - configMapRef:
                name: socket-service-config  # Create a ConfigMap for environment variables
      # Add volumes and volume mounts if needed
